-
  branches:
    only:
      - master

  version: 1.0.9.{build}

  image: Visual Studio 2015

  init:
    - git config --global core.autocrlf input

  configuration: Release

  before_build:
    - ps: Write-Output "envs= $($Env:APPVEYOR_BUILD_VERSION).$($Env:APPVEYOR_BUILD_NUMBER)"
    - ps: Write-Output "Version= {version}"
    #- ps: .\update-version.ps1 -FilePath .\src\RazorJam.AzureSearchServiceBootstrapper\project.json -Version "hello"
    - dotnet restore

  test: off

  artifacts:
    - path: '**\*.nupkg'
      name: nuget_package

  deploy:
    - provider: Environment
      name: nuget.org

  on_failure:
    - ps: Update-AppveyorBuild -Version "$($Env:APPVEYOR_BUILD_VERSION).$($Env:APPVEYOR_BUILD_NUMBER)-fail"