-
  branches:
    only:
      - master

  version: 1.0.7.{build}

  image: Visual Studio 2015

  init:
    - git config --global core.autocrlf input
  
  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: AssemblyInfo.*
    patch: true

  configuration: Release

  before build:
   - dotnet restore

  test: off

  artifacts:
    - path: **\*.nupkg

  on_failure:
    - ps: Update-AppveyorBuild -Version "$($Env:APPVEYOR_BUILD_VERSION).$($Env:APPVEYOR_BUILD_NUMBER)-fail"