-
  branches:
    only:
      - master

  version: 1.0.9.{build}

  image: Visual Studio 2015

  init:
    - git config --global core.autocrlf input

  configuration: Release

  before_build:
    - dotnet restore

  after_build:
    - ps: dotnet pack --no-build --configuration %compile:Configuration% --version-suffix "$($Env:APPVEYOR_BUILD_VERSION)"

  test: off

  artifacts:
    - path: '**\*.nupkg'
      name: nuget_package

  deploy:
    - provider: Environment
      name: nuget.org

  on_failure:
    - ps: Update-AppveyorBuild -Version "$($Env:APPVEYOR_BUILD_VERSION).$($Env:APPVEYOR_BUILD_NUMBER)-fail"