-
  branches:
    only:
      - master

  version: 1.0.9.{build}

  image: Visual Studio 2015

  init:
    - git config --global core.autocrlf input

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  configuration: Release

  before_build:
   - dotnet restore
   - ps: echo $NugetApiKey

  test: off

  artifacts:
    - path: '**\*.nupkg'
      name: 'nuget_package.nupkg'

  deploy:
    - provider: NuGet
      server: https://www.nuget.org/api/v2/package
      api_key:
        secure: $NugetApiKey
      skip_symbols: true
      artifact: nuget_package.nupkg

  on_failure:
    - ps: Update-AppveyorBuild -Version "$($Env:APPVEYOR_BUILD_VERSION).$($Env:APPVEYOR_BUILD_NUMBER)-fail"